menu:
  - title: Home
    link: /
  - title: About
    link: /about/
  - title: Architecture
    link: /category/architecture/
    color: architecture
  - title: Azure
    link: /category/azure/
    color: azure
  - title: "C#"
    link: /category/csharp/
    color: csharp
    submenu:
      - title: Visual Studio
        link: /category/visual-studio/
      - title: SQL
        link: /category/sql/
  - title: Machine Learning
    link: /category/machine-learning/
    color: machine-learning
  - title: Microsoft 365
    link: /category/microsoft-365/
    color: microsoft-365
    submenu:
      - title: Office
        link: /category/office/
      - title: CRM
        link: /category/dynamics-crm/
      - title: SharePoint
        link: /category/sharepoint/
      - title: Project Server
        link: /category/project-server/
  - title: PowerShell
    link: /category/powershell/
    color: powershell
  - title: Windows
    link: /category/windows/
    color: windows
    submenu:
      - title: Hyper-V
        link: /category/hyper-v/
      - title: Surface
        link: /category/surface/
      - title: Windows Phone
        link: /category/windows-phone/
